// list of countries with their flag emojis for profile
export const COUNTRIES = [
    { label: 'Afghanistan', value: 'Afghanistan', emoji: '🇦🇫' },
    { label: 'Albania', value: 'Albania', emoji: '🇦🇱' },
    { label: 'Algeria', value: 'Algeria', emoji: '🇩🇿' },
    { label: 'Andorra', value: 'Andorra', emoji: '🇦🇩' },
    { label: 'Angola', value: 'Angola', emoji: '🇦🇴' },
    { label: 'Antigua & Barbuda', value: 'Antigua & Barbuda', emoji: '🇦🇬' },
    { label: 'Argentina', value: 'Argentina', emoji: '🇦🇷' },
    { label: 'Armenia', value: 'Armenia', emoji: '🇦🇲' },
    { label: 'Australia', value: 'Australia', emoji: '🇦🇺' },
    { label: 'Austria', value: 'Austria', emoji: '🇦🇹' },
    { label: 'Azerbaijan', value: 'Azerbaijan', emoji: '🇦🇿' },
    { label: 'Bahamas', value: 'Bahamas', emoji: '🇧🇸' },
    { label: 'Bahrain', value: 'Bahrain', emoji: '🇧🇭' },
    { label: 'Bangladesh', value: 'Bangladesh', emoji: '🇧🇩' },
    { label: 'Barbados', value: 'Barbados', emoji: '🇧🇧' },
    { label: 'Belarus', value: 'Belarus', emoji: '🇧🇾' },
    { label: 'Belgium', value: 'Belgium', emoji: '🇧🇪' },
    { label: 'Belize', value: 'Belize', emoji: '🇧🇿' },
    { label: 'Benin', value: 'Benin', emoji: '🇧🇯' },
    { label: 'Bhutan', value: 'Bhutan', emoji: '🇧🇹' },
    { label: 'Bolivia', value: 'Bolivia', emoji: '🇧🇴' },
    { label: 'Bosnia & Herzegovina', value: 'Bosnia & Herzegovina', emoji: '🇧🇦' },
    { label: 'Botswana', value: 'Botswana', emoji: '🇧🇼' },
    { label: 'Brazil', value: 'Brazil', emoji: '🇧🇷' },
    { label: 'Brunei', value: 'Brunei', emoji: '🇧🇳' },
    { label: 'Bulgaria', value: 'Bulgaria', emoji: '🇧🇬' },
    { label: 'Burkina Faso', value: 'Burkina Faso', emoji: '🇧🇫' },
    { label: 'Burundi', value: 'Burundi', emoji: '🇧🇮' },
    { label: 'Cabo Verde', value: 'Cabo Verde', emoji: '🇨🇻' },
    { label: 'Cambodia', value: 'Cambodia', emoji: '🇰🇭' },
    { label: 'Cameroon', value: 'Cameroon', emoji: '🇨🇲' },
    { label: 'Canada', value: 'Canada', emoji: '🇨🇦' },
    { label: 'Central African Republic', value: 'Central African Republic', emoji: '🇨🇫' },
    { label: 'Chad', value: 'Chad', emoji: '🇹🇩' },
    { label: 'Chile', value: 'Chile', emoji: '🇨🇱' },
    { label: 'China', value: 'China', emoji: '🇨🇳' },
    { label: 'Colombia', value: 'Colombia', emoji: '🇨🇴' },
    { label: 'Comoros', value: 'Comoros', emoji: '🇰🇲' },
    { label: 'Congo', value: 'Congo', emoji: '🇨🇬' },
    { label: 'Costa Rica', value: 'Costa Rica', emoji: '🇨🇷' },
    { label: 'Croatia', value: 'Croatia', emoji: '🇭🇷' },
    { label: 'Cuba', value: 'Cuba', emoji: '🇨🇺' },
    { label: 'Cyprus', value: 'Cyprus', emoji: '🇨🇾' },
    { label: 'Czech Republic', value: 'Czech Republic', emoji: '🇨🇿' },
    { label: 'Denmark', value: 'Denmark', emoji: '🇩🇰' },
    { label: 'Djibouti', value: 'Djibouti', emoji: '🇩🇯' },
    { label: 'Dominica', value: 'Dominica', emoji: '🇩🇲' },
    { label: 'Dominican Republic', value: 'Dominican Republic', emoji: '🇩🇴' },
    { label: 'DR Congo', value: 'DR Congo', emoji: '🇨🇩' },
    { label: 'Ecuador', value: 'Ecuador', emoji: '🇪🇨' },
    { label: 'Egypt', value: 'Egypt', emoji: '🇪🇬' },
    { label: 'El Salvador', value: 'El Salvador', emoji: '🇸🇻' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea', emoji: '🇬🇶' },
    { label: 'Eritrea', value: 'Eritrea', emoji: '🇪🇷' },
    { label: 'Estonia', value: 'Estonia', emoji: '🇪🇪' },
    { label: 'Eswatini', value: 'Eswatini', emoji: '🇸🇿' },
    { label: 'Ethiopia', value: 'Ethiopia', emoji: '🇪🇹' },
    { label: 'Fiji', value: 'Fiji', emoji: '🇫🇯' },
    { label: 'Finland', value: 'Finland', emoji: '🇫🇮' },
    { label: 'France', value: 'France', emoji: '🇫🇷' },
    { label: 'Gabon', value: 'Gabon', emoji: '🇬🇦' },
    { label: 'Gambia', value: 'Gambia', emoji: '🇬🇲' },
    { label: 'Georgia', value: 'Georgia', emoji: '🇬🇪' },
    { label: 'Germany', value: 'Germany', emoji: '🇩🇪' },
    { label: 'Ghana', value: 'Ghana', emoji: '🇬🇭' },
    { label: 'Greece', value: 'Greece', emoji: '🇬🇷' },
    { label: 'Grenada', value: 'Grenada', emoji: '🇬🇩' },
    { label: 'Guatemala', value: 'Guatemala', emoji: '🇬🇹' },
    { label: 'Guinea', value: 'Guinea', emoji: '🇬🇳' },
    { label: 'Guinea-Bissau', value: 'Guinea-Bissau', emoji: '🇬🇼' },
    { label: 'Guyana', value: 'Guyana', emoji: '🇬🇾' },
    { label: 'Haiti', value: 'Haiti', emoji: '🇭🇹' },
    { label: 'Honduras', value: 'Honduras', emoji: '🇭🇳' },
    { label: 'Hungary', value: 'Hungary', emoji: '🇭🇺' },
    { label: 'Iceland', value: 'Iceland', emoji: '🇮🇸' },
    { label: 'India', value: 'India', emoji: '🇮🇳' },
    { label: 'Indonesia', value: 'Indonesia', emoji: '🇮🇩' },
    { label: 'Iran', value: 'Iran', emoji: '🇮🇷' },
    { label: 'Iraq', value: 'Iraq', emoji: '🇮🇶' },
    { label: 'Ireland', value: 'Ireland', emoji: '🇮🇪' },
    { label: 'Israel', value: 'Israel', emoji: '🇮🇱' },
    { label: 'Italy', value: 'Italy', emoji: '🇮🇹' },
    { label: 'Jamaica', value: 'Jamaica', emoji: '🇯🇲' },
    { label: 'Japan', value: 'Japan', emoji: '🇯🇵' },
    { label: 'Jordan', value: 'Jordan', emoji: '🇯🇴' },
    { label: 'Kazakhstan', value: 'Kazakhstan', emoji: '🇰🇿' },
    { label: 'Kenya', value: 'Kenya', emoji: '🇰🇪' },
    { label: 'Kiribati', value: 'Kiribati', emoji: '🇰🇮' },
    { label: 'Kosovo', value: 'Kosovo', emoji: '🇽🇰' },
    { label: 'Kuwait', value: 'Kuwait', emoji: '🇰🇼' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan', emoji: '🇰🇬' },
    { label: 'Laos', value: 'Laos', emoji: '🇱🇦' },
    { label: 'Latvia', value: 'Latvia', emoji: '🇱🇻' },
    { label: 'Lebanon', value: 'Lebanon', emoji: '🇱🇧' },
    { label: 'Lesotho', value: 'Lesotho', emoji: '🇱🇸' },
    { label: 'Liberia', value: 'Liberia', emoji: '🇱🇷' },
    { label: 'Libya', value: 'Libya', emoji: '🇱🇾' },
    { label: 'Liechtenstein', value: 'Liechtenstein', emoji: '🇱🇮' },
    { label: 'Lithuania', value: 'Lithuania', emoji: '🇱🇹' },
    { label: 'Luxembourg', value: 'Luxembourg', emoji: '🇱🇺' },
    { label: 'Madagascar', value: 'Madagascar', emoji: '🇲🇬' },
    { label: 'Malawi', value: 'Malawi', emoji: '🇲🇼' },
    { label: 'Malaysia', value: 'Malaysia', emoji: '🇲🇾' },
    { label: 'Maldives', value: 'Maldives', emoji: '🇲🇻' },
    { label: 'Mali', value: 'Mali', emoji: '🇲🇱' },
    { label: 'Malta', value: 'Malta', emoji: '🇲🇹' },
    { label: 'Marshall Islands', value: 'Marshall Islands', emoji: '🇲🇭' },
    { label: 'Mauritania', value: 'Mauritania', emoji: '🇲🇷' },
    { label: 'Mauritius', value: 'Mauritius', emoji: '🇲🇺' },
    { label: 'Mexico', value: 'Mexico', emoji: '🇲🇽' },
    { label: 'Micronesia', value: 'Micronesia', emoji: '🇫🇲' },
    { label: 'Moldova', value: 'Moldova', emoji: '🇲🇩' },
    { label: 'Monaco', value: 'Monaco', emoji: '🇲🇨' },
    { label: 'Mongolia', value: 'Mongolia', emoji: '🇲🇳' },
    { label: 'Montenegro', value: 'Montenegro', emoji: '🇲🇪' },
    { label: 'Morocco', value: 'Morocco', emoji: '🇲🇦' },
    { label: 'Mozambique', value: 'Mozambique', emoji: '🇲🇿' },
    { label: 'Myanmar', value: 'Myanmar', emoji: '🇲🇲' },
    { label: 'Namibia', value: 'Namibia', emoji: '🇳🇦' },
    { label: 'Nauru', value: 'Nauru', emoji: '🇳🇷' },
    { label: 'Nepal', value: 'Nepal', emoji: '🇳🇵' },
    { label: 'Netherlands', value: 'Netherlands', emoji: '🇳🇱' },
    { label: 'New Zealand', value: 'New Zealand', emoji: '🇳🇿' },
    { label: 'Nicaragua', value: 'Nicaragua', emoji: '🇳🇮' },
    { label: 'Niger', value: 'Niger', emoji: '🇳🇪' },
    { label: 'Nigeria', value: 'Nigeria', emoji: '🇳🇬' },
    { label: 'North Korea', value: 'North Korea', emoji: '🇰🇵' },
    { label: 'North Macedonia', value: 'North Macedonia', emoji: '🇲🇰' },
    { label: 'Norway', value: 'Norway', emoji: '🇳🇴' },
    { label: 'Oman', value: 'Oman', emoji: '🇴🇲' },
    { label: 'Pakistan', value: 'Pakistan', emoji: '🇵🇰' },
    { label: 'Palau', value: 'Palau', emoji: '🇵🇼' },
    { label: 'Palestine', value: 'Palestine', emoji: '🇵🇸' },
    { label: 'Panama', value: 'Panama', emoji: '🇵🇦' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea', emoji: '🇵🇬' },
    { label: 'Paraguay', value: 'Paraguay', emoji: '🇵🇾' },
    { label: 'Peru', value: 'Peru', emoji: '🇵🇪' },
    { label: 'Philippines', value: 'Philippines', emoji: '🇵🇭' },
    { label: 'Poland', value: 'Poland', emoji: '🇵🇱' },
    { label: 'Portugal', value: 'Portugal', emoji: '🇵🇹' },
    { label: 'Qatar', value: 'Qatar', emoji: '🇶🇦' },
    { label: 'Romania', value: 'Romania', emoji: '🇷🇴' },
    { label: 'Russia', value: 'Russia', emoji: '🇷🇺' },
    { label: 'Rwanda', value: 'Rwanda', emoji: '🇷🇼' },
    { label: 'Saint Kitts & Nevis', value: 'Saint Kitts & Nevis', emoji: '🇰🇳' },
    { label: 'Saint Lucia', value: 'Saint Lucia', emoji: '🇱🇨' },
    { label: 'Saint Vincent & the Grenadines', value: 'Saint Vincent & the Grenadines', emoji: '🇻🇨' },
    { label: 'Samoa', value: 'Samoa', emoji: '🇼🇸' },
    { label: 'San Marino', value: 'San Marino', emoji: '🇸🇲' },
    { label: 'São Tomé & Príncipe', value: 'São Tomé & Príncipe', emoji: '🇸🇹' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia', emoji: '🇸🇦' },
    { label: 'Senegal', value: 'Senegal', emoji: '🇸🇳' },
    { label: 'Serbia', value: 'Serbia', emoji: '🇷🇸' },
    { label: 'Seychelles', value: 'Seychelles', emoji: '🇸🇨' },
    { label: 'Sierra Leone', value: 'Sierra Leone', emoji: '🇸🇱' },
    { label: 'Singapore', value: 'Singapore', emoji: '🇸🇬' },
    { label: 'Slovakia', value: 'Slovakia', emoji: '🇸🇰' },
    { label: 'Slovenia', value: 'Slovenia', emoji: '🇸🇮' },
    { label: 'Solomon Islands', value: 'Solomon Islands', emoji: '🇸🇧' },
    { label: 'Somalia', value: 'Somalia', emoji: '🇸🇴' },
    { label: 'South Africa', value: 'South Africa', emoji: '🇿🇦' },
    { label: 'South Korea', value: 'South Korea', emoji: '🇰🇷' },
    { label: 'South Sudan', value: 'South Sudan', emoji: '🇸🇸' },
    { label: 'Spain', value: 'Spain', emoji: '🇪🇸' },
    { label: 'Sri Lanka', value: 'Sri Lanka', emoji: '🇱🇰' },
    { label: 'Sudan', value: 'Sudan', emoji: '🇸🇩' },
    { label: 'Suriname', value: 'Suriname', emoji: '🇸🇷' },
    { label: 'Sweden', value: 'Sweden', emoji: '🇸🇪' },
    { label: 'Switzerland', value: 'Switzerland', emoji: '🇨🇭' },
    { label: 'Syria', value: 'Syria', emoji: '🇸🇾' },
    { label: 'Taiwan', value: 'Taiwan', emoji: '🇹🇼' },
    { label: 'Tajikistan', value: 'Tajikistan', emoji: '🇹🇯' },
    { label: 'Tanzania', value: 'Tanzania', emoji: '🇹🇿' },
    { label: 'Thailand', value: 'Thailand', emoji: '🇹🇭' },
    { label: 'Timor-Leste', value: 'Timor-Leste', emoji: '🇹🇱' },
    { label: 'Togo', value: 'Togo', emoji: '🇹🇬' },
    { label: 'Tonga', value: 'Tonga', emoji: '🇹🇴' },
    { label: 'Trinidad & Tobago', value: 'Trinidad & Tobago', emoji: '🇹🇹' },
    { label: 'Tunisia', value: 'Tunisia', emoji: '🇹🇳' },
    { label: 'Turkey', value: 'Turkey', emoji: '🇹🇷' },
    { label: 'Turkmenistan', value: 'Turkmenistan', emoji: '🇹🇲' },
    { label: 'Tuvalu', value: 'Tuvalu', emoji: '🇹🇻' },
    { label: 'Uganda', value: 'Uganda', emoji: '🇺🇬' },
    { label: 'Ukraine', value: 'Ukraine', emoji: '🇺🇦' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates', emoji: '🇦🇪' },
    { label: 'United Kingdom', value: 'United Kingdom', emoji: '🇬🇧' },
    { label: 'United States', value: 'United States', emoji: '🇺🇸' },
    { label: 'Uruguay', value: 'Uruguay', emoji: '🇺🇾' },
    { label: 'Uzbekistan', value: 'Uzbekistan', emoji: '🇺🇿' },
    { label: 'Vanuatu', value: 'Vanuatu', emoji: '🇻🇺' },
    { label: 'Vatican City', value: 'Vatican City', emoji: '🇻🇦' },
    { label: 'Venezuela', value: 'Venezuela', emoji: '🇻🇪' },
    { label: 'Vietnam', value: 'Vietnam', emoji: '🇻🇳' },
    { label: 'Yemen', value: 'Yemen', emoji: '🇾🇪' },
    { label: 'Zambia', value: 'Zambia', emoji: '🇿🇲' },
    { label: 'Zimbabwe', value: 'Zimbabwe', emoji: '🇿🇼' },
  ];